version: 2.1

orbs:
  lint-orb: kumailf/lint-orb@0.0.1

jobs:
  build:
    executor: kumailf/lint-orb
    steps:
      - lint-orb/lint:
          url: git@github.com:kumailf/mmdeploy.git

workflows:
  lint:
    jobs:
      - build